

# Load Bot Api
$getMeLink = "https://api.telegram.org/bot$botkey/getMe"
$sendMessageLink = "https://api.telegram.org/bot$botkey/sendMessage"
$getUpdatesLink = "https://api.telegram.org/bot$botkey/getUpdates"
$sendPhotoLink = "https://api.telegram.org/bot$botkey/sendPhoto"
$sendAudioLink = "https://api.telegram.org/bot$botkey/sendAudio"
$sendDocumentLink = "https://api.telegram.org/bot$botkey/sendDocument"
$sendVideoLink = "https://api.telegram.org/bot$botkey/sendVideo"
$getFileLink = "https://api.telegram.org/bot$botkey/getFile"
$getFilePathLink = "https://api.telegram.org/file/bot$botkey/"
$kickChatMemberLink = "https://api.telegram.org/bot$botkey/kickChatMember"
$promoteChatMemberLink = "https://api.telegram.org/bot$botkey/promoteChatMember"
$exportChatInviteLink = "https://api.telegram.org/bot$botkey/exportChatInviteLink"
$setChatTitleLink = "https://api.telegram.org/bot$botkey/setChatTitle"
$pinChatMessageLink = "https://api.telegram.org/bot$botkey/pinChatMessage"
$unpinChatMessageLink = "https://api.telegram.org/bot$botkey/unpinChatMessage"
$getChatLink = "https://api.telegram.org/bot$botkey/getChat"
$getChatAdministratorsLink = "https://api.telegram.org/bot$botkey/getChatAdministrators"
$getChatMemberLink = "https://api.telegram.org/bot$botkey/getChatMember"
$getChatMembersCountLink = "https://api.telegram.org/bot$botkey/getChatMembersCount"